"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-06-29 23:28:43.153037

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=True),
        sa.Column("agent_kind", sa.String(), nullable=False),
        sa.Column("agent_runtime_arn", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("endpoint_url", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("multimodal", sa.Boolean(), nullable=False),
        sa.Column("suggested_questions", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(agent_kind = 'agentcore_runtime' AND agent_runtime_arn IS NOT NULL AND endpoint_url IS NULL) OR (agent_kind = 'local' AND endpoint_url IS NOT NULL AND agent_runtime_arn IS NULL AND region IS NULL)",
            name="ck_agents_kind_columns",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "model_pricing",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("input_token_price", sa.Float(), nullable=False),
        sa.Column("output_token_price", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_id", "provider", name="uq_model_pricing_model_provider"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("auth_provider", sa.String(), nullable=False),
        sa.Column("external_subject", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("location", sa.String(length=256), nullable=True),
        sa.Column("company", sa.String(length=256), nullable=True),
        sa.Column("department", sa.String(length=256), nullable=True),
        sa.Column("budget", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("budget >= 0.0", name="check_user_budget_positive"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            "uq_users_provider_subject",
            ["auth_provider", "external_subject"],
            unique=True,
            sqlite_where=sa.text("external_subject IS NOT NULL"),
            postgresql_where=sa.text("external_subject IS NOT NULL"),
        )

    op.create_table(
        "agent_groups",
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("group_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("agent_id", "group_id"),
    )
    with op.batch_alter_table("agent_groups", schema=None) as batch_op:
        batch_op.create_index("ix_agent_groups_group_id", ["group_id"], unique=False)

    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("secret_hash"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index("ix_api_keys_secret_hash", ["secret_hash"], unique=True)
        batch_op.create_index("ix_api_keys_user_id", ["user_id"], unique=False)

    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=256), nullable=False),
        sa.Column("agent_id", sa.String(length=36), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=True),
        sa.Column("manifest_captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "length(session_id) >= 33 AND length(session_id) <= 256",
            name="ck_chat_sessions_session_id_length",
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chat_sessions_user_last_used",
            ["user_id", "last_used_at"],
            unique=False,
            postgresql_ops={"last_used_at": "DESC"},
        )
        batch_op.create_index(
            "ix_chat_sessions_user_session", ["user_id", "session_id"], unique=False
        )

    op.create_table(
        "user_groups",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("group_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
    )
    with op.batch_alter_table("user_groups", schema=None) as batch_op:
        batch_op.create_index("ix_user_groups_group_id", ["group_id"], unique=False)

    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chat_session_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("is_success", sa.Boolean(), nullable=False),
        sa.Column("attachments", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('user','assistant')", name="ck_chat_messages_role"),
        sa.ForeignKeyConstraint(["chat_session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_session_id", "seq", name="uq_chat_messages_session_seq"),
    )
    op.create_table(
        "token_usage",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("chat_session_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("agent_name", sa.String(), nullable=False),
        sa.Column("model_id", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("cost >= 0.0", name="check_token_usage_cost_positive"),
        sa.ForeignKeyConstraint(["chat_session_id"], ["chat_sessions.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("token_usage", schema=None) as batch_op:
        batch_op.create_index("ix_token_usage_session", ["chat_session_id"], unique=False)
        batch_op.create_index(
            "ix_token_usage_user_created",
            ["user_id", "created_at"],
            unique=False,
            postgresql_ops={"created_at": "DESC"},
        )
        batch_op.create_index("ix_token_usage_user_id", ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("token_usage", schema=None) as batch_op:
        batch_op.drop_index("ix_token_usage_user_id")
        batch_op.drop_index("ix_token_usage_user_created", postgresql_ops={"created_at": "DESC"})
        batch_op.drop_index("ix_token_usage_session")

    op.drop_table("token_usage")
    op.drop_table("chat_messages")
    with op.batch_alter_table("user_groups", schema=None) as batch_op:
        batch_op.drop_index("ix_user_groups_group_id")

    op.drop_table("user_groups")
    with op.batch_alter_table("chat_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_chat_sessions_user_session")
        batch_op.drop_index(
            "ix_chat_sessions_user_last_used", postgresql_ops={"last_used_at": "DESC"}
        )

    op.drop_table("chat_sessions")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index("ix_api_keys_user_id")
        batch_op.drop_index("ix_api_keys_secret_hash")

    op.drop_table("api_keys")
    with op.batch_alter_table("agent_groups", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_groups_group_id")

    op.drop_table("agent_groups")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_users_provider_subject",
            sqlite_where=sa.text("external_subject IS NOT NULL"),
            postgresql_where=sa.text("external_subject IS NOT NULL"),
        )

    op.drop_table("users")
    op.drop_table("model_pricing")
    op.drop_table("groups")
    op.drop_table("agents")
    # ### end Alembic commands ###
